$(function(){
	$(".bundle").mouseover(function(){
		$(this).addClass('abc');
		$(this).siblings().addClass('qqd');
	}).mouseout(function(){
		$(this).removeClass('abc');
		$(this).siblings().removeClass('qqd');
	})
})
